################################# Default configuration ###################

baseURL = "https://chrisbailey-za.github.io/"
languageCode = "en-us"
title = "Chris Bailey Analytics"
theme = "aero"
paginate = 5



#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

  
############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 4

[[menu.main]]
name = "Services"
URL = "service"
weight = 2

[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

# footer menu
[[menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[menu.footer]]
name = "Contact"
URL = "/#contact"
weight = 4

[[menu.footer]]
name = "Email Me"
URL = "mailto:chris@chrisbaileyanalytics.com"
weight = 5

[[menu.footer]]
name = "LinkedIn"
URL = "https://www.linkedin.com/in/chris-bailey-analytics/"
weight = 6

[[menu.footer]]
name = "UpWork"
URL = "https://www.upwork.com/freelancers/~01ae9a9043ad0d53c7"
weight = 7



#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Freelance Digital Analytics Consultant - Helping you to make sense of your digital analytics data."
author = "Chris Bailey"
# Contact Information
email = "chris@chrisbaileyanalytics.com"
location = "Cape Town, South Africa"
# contact form action
contact_form_action = "https://getform.io/f/5551a630-e2bb-4ef5-9af2-9d2631866260"
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = false

  
############################# social site ########################

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"
